package com.lianshang.generator.format;

import com.lianshang.generator.constant.Constant;
import com.lianshang.generator.exception.ServiceException;
import com.lianshang.generator.meta.TableMeta;
import com.lianshang.generator.util.Tools;

/**
 * Created by walker on 16/2/16.
 */
public class AugularListControllerFormat {

    public static String getFileContent(String className, String prefixClassPackage, TableMeta meta) throws ServiceException {
        String tableName = Tools.lineToHump(meta.getTableName());

        StringBuilder builder = new StringBuilder();
        builder.append("(function () {\n"
            + "\n"
            + "  ActivityMgmtCtrl.$inject = ['$scope', '$http', '$uibModal', '$compile',\n"
            + "    '$filter', 'toaster', 'activityMgmtService', 'DTOptionsBuilder',\n"
            + "    'DTColumnBuilder', '$state'];\n"
            + "\n"
            + "  function ActivityMgmtCtrl($scope, $http, $uibModal, $compile, $filter,\n"
            + "      toaster, activityMgmtService, DTOptionsBuilder, DTColumnBuilder, $state) {\n"
            + "\n"
            + "    var vm = this;\n"
            + "    var rootCtrlScope = $scope;\n"
            + "    vm.title = '';\n"
            + "    vm.id = \"\";\n"
            + "    vm.status = 0;\n"
            + "    vm.activityId = 0;\n"
            + "    var dateTime = new Date();\n"
            + "    vm.reStartDate = $filter('date')(\n"
            + "            new Date((dateTime / 1000 - 2592000) * 1000), 'yyyy-MM-dd')\n"
            + "        + \" 00:00:00\";\n"
            + "    vm.reEndDate = $filter('date')(new Date(), 'yyyy-MM-dd') + \" 23:59:59\";\n"
            + "\n"
            + "    vm.reValidateDateRange = {\n"
            + "      startDate: vm.reStartDate,\n"
            + "      endDate: vm.reEndDate\n"
            + "    }\n"
            + "\n"
            + "    $scope.$watch('vm.reValidateDateRange', function (newVal, oldVal) {\n"
            + "      if (newVal) {\n"
            + "        vm.reStartDate = moment(newVal.startDate, \"YYYY-MM-DD hh:mm:ss\").format(\n"
            + "            \"YYYY-MM-DD HH:mm:ss\");\n"
            + "        vm.reEndDate = moment(newVal.endDate, \"YYYY-MM-DD hh:mm:ss\").format(\n"
            + "            \"YYYY-MM-DD HH:mm:ss\");\n"
            + "      }\n"
            + "    });\n"
            + "\n"
            + "    vm.opts = {\n"
            + "      locale: {\n"
            + "        applyClass: 'btn-green',\n"
            + "        applyLabel: \"应用\",\n"
            + "        fromLabel: \"从\",\n"
            + "        format: \"YYYY-MM-DD HH:mm\",\n"
            + "        toLabel: \"至\",\n"
            + "        cancelLabel: '取消',\n"
            + "        customRangeLabel: '自定义区间'\n"
            + "      },\n"
            + "      ranges: {\n"
            + "        '近1天': [moment().subtract(1, 'days'), moment()],\n"
            + "        '近7天': [moment().subtract(6, 'days'), moment()],\n"
            + "        '近30天': [moment().subtract(29, 'days'), moment()]\n"
            + "      }\n"
            + "    }\n"
            + "\n"
            + "    $scope.dtInstance = {};\n"
            + "\n"
            + "    $scope.dtOptions = DTOptionsBuilder\n"
            + "    .fromSource('')\n"
            + "    .withFnServerData(serverData)\n"
            + "    .withDataProp('data')\n"
            + "    .withOption('serverSide', true)\n"
            + "    .withOption('searching', false)\n"
            + "    .withOption('lengthChange', true)\n"
            + "    .withOption('autoWidth', false)\n"
            + "    .withOption('scrollX', false)\n"
            + "    .withOption('lengthMenu', [10, 25, 50, 100])\n"
            + "    .withOption('displayLength', 10)\n"
            + "    .withPaginationType('full_numbers')\n"
            + "    .withOption('createdRow', function (row, data, dataIndex) {\n"
            + "      $compile(angular.element(row).contents())($scope);\n"
            + "    });\n"
            + "\n"
            + "    $scope.dtColumns = [\n"
            + "      //DTColumnBuilder.newColumn(null).withTitle('').notVisible(),\n"
            + "      DTColumnBuilder.newColumn('id').withTitle('活动ID'),\n"
            + "      DTColumnBuilder.newColumn('title').withTitle('活动名称').notSortable(),\n"
            + "      DTColumnBuilder.newColumn('updateTime').withTitle('更新时间').renderWith(\n"
            + "          updateTimeHtml),\n"
            + "      DTColumnBuilder.newColumn('status').withTitle('活动状态').renderWith(\n"
            + "          statusHtml),\n"
            + "      DTColumnBuilder.newColumn(null).withTitle('操作').notSortable().withClass(\n"
            + "          'text-center p-w-xxs-i')\n"
            + "      .withOption('width', ' 90px').renderWith(actionsHtml)\n"
            + "    ];\n"
            + "\n"
            + "    function serverData(sSource, aoData, fnCallback, oSettings) {\n"
            + "\n"
            + "      var draw = aoData[0].value;\n"
            + "      var sortColumn = $scope.dtColumns[parseInt(\n"
            + "          aoData[2].value[0].column)].mData;\n"
            + "      var sortDir = aoData[2].value[0].dir;\n"
            + "      var start = aoData[3].value;\n"
            + "      var limit = aoData[4].value;\n"
            + "\n"
            + "      if (vm.status == null || vm.status === '') {\n"
            + "        vm.status = -1;\n"
            + "      }\n"
            + "\n"
            + "      return activityMgmtService.queryActivityList(vm.title, vm.status,\n"
            + "          vm.reStartDate, vm.reEndDate, draw, sortColumn, sortDir, start, limit)\n"
            + "      .then(function (resp) {\n"
            + "        fnCallback(resp.data);\n"
            + "        vm.tableData = resp.data;\n"
            + "      }).finally(function () {\n"
            + "        $scope.queryBtnDisabled = false;\n"
            + "      });\n"
            + "\n"
            + "    }\n"
            + "\n"
            + "    function actionsHtml(data, type, full, meta) {\n"
            + "      var str = '';\n"
            + "      str += '<button ng-disabled=\"banShopButn\" class=\"btn btn-xs btn-blue btn-rounded\" ng-click=\"editActivity('\n"
            + "          + '\\'' + data.id + '\\',\\'' + data.title + '\\')\">' +\n"
            + "          '    <i class=\"fa fa-bolt\">活动管理</i>' +\n"
            + "          '</button>&nbsp;&nbsp;';\n"
            + "      str += '<button ng-disabled=\"banShopButn\" class=\"btn btn-xs btn-blue btn-rounded\" ng-click=\"editPage('\n"
            + "          + '\\'' + data.id + '\\'' + ')\">' +\n"
            + "          '    <i class=\"fa fa-bolt\">活动页面编辑</i>' +\n"
            + "          '</button>&nbsp;&nbsp;';\n"
            + "\n"
            + "      if (full.status == 1) {\n"
            + "        str += '<button ng-disabled=\"banShopButn\" class=\"btn btn-xs btn-success btn-rounded\" ng-click=\"banShop('\n"
            + "            + full.id + ',\\'' + 2 + '\\')\">' +\n"
            + "            '    <i class=\"fa fa-bolt\">上线</i>' +\n"
            + "            '</button>&nbsp;&nbsp;';\n"
            + "      } else {\n"
            + "        str += '<button ng-disabled=\"\" class=\"btn btn-xs btn-danger btn-rounded\" ng-click=\"banShop('\n"
            + "            + full.id + ',\\'' + 1 + '\\')\">' +\n"
            + "            '    <i class=\"fa fa-bolt\">下线</i>' +\n"
            + "            '</button>&nbsp;&nbsp;';\n"
            + "      }\n"
            + "      return str;\n"
            + "    }\n"
            + "\n"
            + "    function updateTimeHtml(data, type, full, meta) {\n"
            + "      return $filter('date')(full.updateTime, 'yyyy-MM-dd HH:mm:ss');\n"
            + "    }\n"
            + "\n"
            + "    function statusHtml(data, type, full, meta) {\n"
            + "\n"
            + "      var str = '';\n"
            + "\n"
            + "      if (full.status == 2) {\n"
            + "        str = '<span class=\"label label-success\">' + \"上线\" + '</span>';\n"
            + "      } else if (full.status == 1) {\n"
            + "        str = '<span class=\"label label-danger\">' + \"下线\" + '</span>';\n"
            + "      }\n"
            + "\n"
            + "      return str;\n"
            + "    }\n"
            + "\n"
            + "    $scope.addActivity = function () {\n"
            + "      var opener = $scope\n"
            + "      var modalInstance;\n"
            + "      modalInstance = $uibModal.open({\n"
            + "        templateUrl: 'app/activity-mgmt/modal/add-activity.html',\n"
            + "        size: 'lg',\n"
            + "        controller: function ($scope, $uibModal, $uibModalInstance) {\n"
            + "          $scope.nextBtnDisabled = true;\n"
            + "          $scope.cancel = function () {\n"
            + "            $uibModalInstance.dismiss('cancel');\n"
            + "          };\n"
            + "\n"
            + "          $scope.ok = function () {\n"
            + "            if ($scope.modal.title == undefined) {\n"
            + "              $scope.modal.title = \"\";\n"
            + "            }\n"
            + "            activityMgmtService.addActivity($scope.modal.title)\n"
            + "            .then(function successCallback(response) {\n"
            + "              toaster.pop({\n"
            + "                type: response.data.code == 200 ? '新增成功' : '新增失败',\n"
            + "                title: '提示信息',\n"
            + "                body: response.data.message,\n"
            + "                showCloseButton: true,\n"
            + "                timeout: 5000\n"
            + "              });\n"
            + "              if (response.data.code == 200) {\n"
            + "                opener.dtInstance.reloadData();\n"
            + "                vm.title = $scope.modal.title;\n"
            + "                vm.id = response.data.data;\n"
            + "                // $scope.okBtnDisabled = true;\n"
            + "                // $scope.nextBtnDisabled = false;\n"
            + "                $uibModalInstance.close();\n"
            + "              }\n"
            + "            });\n"
            + "          };\n"
            + "\n"
            + "          // $scope.next = function () {\n"
            + "          //     $uibModalInstance.close();\n"
            + "          // }\n"
            + "        },\n"
            + "        windowClass: 'animated bounceIn'\n"
            + "      });\n"
            + "      modalInstance.result.then(\n"
            + "          function () {\n"
            + "            $uibModal.open({\n"
            + "              templateUrl: 'app/activity-mgmt/modal/edit-activity.html',\n"
            + "              size: 'lg',\n"
            + "              controller: 'sourceMgmtCtrl',\n"
            + "              windowClass: 'animated bounceIn',\n"
            + "              resolve: {\n"
            + "                id: function () {\n"
            + "                  return vm.id;\n"
            + "                },\n"
            + "                title: function () {\n"
            + "                  return vm.title;\n"
            + "                }\n"
            + "              }\n"
            + "            });\n"
            + "          }\n"
            + "      );\n"
            + "    }\n"
            + "\n"
            + "    $scope.editActivity = function (id, title) {\n"
            + "      $uibModal.open({\n"
            + "        templateUrl: 'app/activity-mgmt/modal/edit-activity.html',\n"
            + "        size: 'lg',\n"
            + "        keyboard: false,\n"
            + "        controller: 'sourceMgmtCtrl',\n"
            + "        windowClass: 'animated bounceIn',\n"
            + "        resolve: {\n"
            + "          id: function () {\n"
            + "            return id;\n"
            + "          },\n"
            + "          title: function () {\n"
            + "            return title;\n"
            + "          }\n"
            + "        }\n"
            + "      });\n"
            + "    }\n"
            + "\n"
            + "    $scope.submit = function () {\n"
            + "      $scope.queryBtnDisabled = true;\n"
            + "      $scope.dtInstance.reloadData();\n"
            + "    };\n"
            + "\n"
            + "    $scope.banShop = function (id, type) {\n"
            + "      var modalInstance;\n"
            + "      modalInstance = $uibModal.open({\n"
            + "        templateUrl: 'app/activity-mgmt/modal/confirm-line.html',\n"
            + "        //size: 'lg',\n"
            + "        keyboard: false,\n"
            + "        controller: 'confirmLineCtrl',\n"
            + "        resolve: {\n"
            + "          id: function () {\n"
            + "            return id;\n"
            + "          },\n"
            + "          type: function () {\n"
            + "            return type;\n"
            + "          },\n"
            + "          rootScope: function () {\n"
            + "            return $scope;\n"
            + "          }\n"
            + "        }\n"
            + "\n"
            + "      });\n"
            + "    };\n"
            + "\n"
            + "    $scope.editPage = function (id) {\n"
            + "      //$state.go('activity-mgmt.page-edit',{id: id});\n"
            + "      var modalInstance;\n"
            + "      modalInstance = $uibModal.open({\n"
            + "        templateUrl: 'app/activity-mgmt/modal/page-edit.html',\n"
            + "        size: 'lg',\n"
            + "        keyboard: false,\n"
            + "        controller: 'ActivityEditCtrl',\n"
            + "        resolve: {\n"
            + "          id: function () {\n"
            + "            return id;\n"
            + "          }\n"
            + "        }\n"
            + "\n"
            + "      });\n"
            + "    }\n"
            + "\n"
            + "  }\n"
            + "\n"
            + "  angular\n"
            + "  .module('app.activity-mgmt')\n"
            + "  .controller('ActivityMgmtCtrl', ActivityMgmtCtrl);\n"
            + "\n"
            + "})();");

        return builder.toString();

    }
}
